wandb_version: 1

K:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 64
embed_dim:
  desc: null
  value: 128
n_layer:
  desc: null
  value: 3
n_head:
  desc: null
  value: 1
activation_function:
  desc: null
  value: relu
dropout:
  desc: null
  value: 0.1
learning_rate:
  desc: null
  value: 0.003
weight_decay:
  desc: null
  value: 0.0001
warmup_steps:
  desc: null
  value: 10
num_eval_episodes:
  desc: null
  value: 10
max_iters:
  desc: null
  value: 20000
num_steps_per_iter:
  desc: null
  value: 20000
num_robot:
  desc: null
  value: 1
T:
  desc: null
  value: 200
num_traj:
  desc: null
  value: 1300000
grid_size:
  desc: null
  value: 30
rewardmap_path:
  desc: null
  value: /home/moonlab/decision_transformer/decision_tr/maps/gaussian_mixture_training_data.pkl
wandb:
  desc: null
  value: true
num_shards:
  desc: null
  value: 130
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.44.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1726378540
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.17.8
      6: 4.44.0
      8:
      - 5
      13: linux-x86_64
